package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// The skill is distributed with `npx skills`, which reads SKILL.md files from
// skills/<name>/ and installs them into whichever agent's skills directory the
// reader uses. That file is the only committed copy.
//
// The copy under .claude/ is what this repository's own agents read, because
// that is where Claude Code looks. It is generated by `make skill` and ignored
// by git, so it can never be shipped stale — but it can be hand-edited, and
// these tests say so when it has been.

const (
	skillSource = "skills/interrogate/SKILL.md"
	skillCopy   = ".claude/skills/interrogate/SKILL.md"
)

func TestSkillIsWhereTheInstallerLooks(t *testing.T) {
	// `npx skills` discovers skills at skills/<name>/SKILL.md.
	if _, err := os.Stat(skillSource); err != nil {
		t.Fatalf("the authoritative skill is not where the installer looks: %v", err)
	}
}

func TestOnlyOneCopyOfTheSkillIsCommitted(t *testing.T) {
	// Two committed copies is a drift problem that needs policing. One cannot
	// drift from anything.
	var found []string
	err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			switch info.Name() {
			case ".git", "openspec", "node_modules":
				return filepath.SkipDir
			}
			return nil
		}
		if info.Name() != "SKILL.md" {
			return nil
		}
		if !strings.Contains(path, "interrogate") {
			return nil // the OpenSpec skills are this repository's own tooling
		}
		if path == filepath.FromSlash(skillCopy) {
			return nil // generated and git-ignored
		}
		found = append(found, path)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(found) != 1 || found[0] != filepath.FromSlash(skillSource) {
		t.Errorf("committed copies of the skill = %v, want exactly [%s]", found, skillSource)
	}
}

func TestGeneratedCopyMatchesTheSource(t *testing.T) {
	copied, err := os.ReadFile(skillCopy)
	if os.IsNotExist(err) {
		t.Skipf("no generated copy yet; run `make skill` to create %s", skillCopy)
	}
	if err != nil {
		t.Fatal(err)
	}
	source, err := os.ReadFile(skillSource)
	if err != nil {
		t.Fatal(err)
	}
	if string(source) != string(copied) {
		t.Errorf("%s has been edited by hand.\n%s is authoritative — run `make skill` to regenerate the copy.",
			skillCopy, skillSource)
	}
}

// frontmatterVersion pulls metadata.version out of the skill's frontmatter.
var frontmatterVersion = regexp.MustCompile(`(?m)^\s+version:\s*"?([0-9][0-9A-Za-z.\-]*)"?\s*$`)

func TestSkillDeclaresAVersion(t *testing.T) {
	// The version travels inside the file, so an installed copy reports the
	// version it actually carries. There is nowhere else for it to disagree
	// with.
	raw, err := os.ReadFile(skillSource)
	if err != nil {
		t.Fatal(err)
	}
	match := frontmatterVersion.FindStringSubmatch(string(raw))
	if match == nil {
		t.Fatalf("%s has no metadata.version in its frontmatter, so an installed copy cannot be identified", skillSource)
	}
	if strings.Count(match[1], ".") < 2 {
		t.Errorf("version = %q, want a full major.minor.patch so updates can be compared", match[1])
	}
}

func TestSkillFrontmatterNamesAndDescribesTheSkill(t *testing.T) {
	raw, err := os.ReadFile(skillSource)
	if err != nil {
		t.Fatal(err)
	}
	head, _, found := strings.Cut(strings.TrimPrefix(string(raw), "---\n"), "\n---")
	if !found {
		t.Fatal("the skill has no frontmatter block, so no installer will recognise it")
	}
	if !strings.Contains(head, "name: interrogate") {
		t.Errorf("the frontmatter does not name the skill `interrogate`:\n%s", head)
	}
	if !strings.Contains(head, "description:") {
		t.Error("the frontmatter has no description, so nothing will know when to use it")
	}
}

func TestNoLeftoverPluginManifests(t *testing.T) {
	// The Claude plugin approach was abandoned: it could only ship a whole
	// repository directory.
	for _, path := range []string{".claude-plugin/plugin.json", ".claude-plugin/marketplace.json"} {
		if _, err := os.Stat(path); err == nil {
			t.Errorf("%s is still present, but distribution is through `npx skills` now", path)
		}
	}
}
